version: '3.8'
services:
  db:
    image: mongo:4.2
    container_name: db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - ./data/dump:/dump

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: noussa2000/nodemongoapp:6.0
    restart: always
    container_name: back
    ports:
      - '5000:5000'
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://root:example@db:27017/skill-exchange?authSource=admin

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: noussa2000/frontend:6.0
    restart: always
    container_name: front
    ports:
      - '3000:3000'
    depends_on:
      - backend

volumes:
  mongo-data: