global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'backend'
    static_configs:
      - targets: ['172.29.0.6:5000']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']